# Generated by Django 6.0.3 on 2026-03-25 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_package_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='package',
            old_name='category',
            new_name='processing_time',
        ),
    ]
