# Generated by Django 6.0.3 on 2026-03-25 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_rename_category_package_processing_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='social_media',
        ),
        migrations.AddField(
            model_name='booking',
            name='birthday',
            field=models.DateField(blank=True, null=True),
        ),
    ]
