# Generated by Django 6.0.3 on 2026-03-25 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_remove_booking_social_media_booking_birthday'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='voucher_code',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
