# Generated by Django 6.0.3 on 2026-03-27 14:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_booking_voucher_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreativePackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='creative_packages/')),
            ],
        ),
        migrations.AddField(
            model_name='booking',
            name='creative_package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bookings.creativepackage'),
        ),
    ]
