# Generated by Django 6.0.3 on 2026-03-27 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0006_creativepackage_booking_creative_package'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creativepackage',
            name='image',
        ),
    ]
