# Generated by Django 6.0.3 on 2026-03-27 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0007_remove_creativepackage_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creativepackage',
            name='description',
        ),
        migrations.AddField(
            model_name='creativepackage',
            name='color',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
