# Generated by Django 6.0.3 on 2026-04-06 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0013_booking_cancellation_reason'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title/description of the image', max_length=100)),
                ('image', models.ImageField(help_text='Upload gallery image', upload_to='gallery/')),
                ('category', models.CharField(choices=[('portrait', 'Portrait Session'), ('wedding', 'Wedding'), ('family', 'Family'), ('event', 'Event'), ('self_portrait', 'Self Portrait'), ('studio', 'Studio Setup'), ('other', 'Other')], default='portrait', max_length=50)),
                ('is_active', models.BooleanField(default=True, help_text='Show in gallery')),
                ('order', models.IntegerField(default=0, help_text='Display order (lower numbers first)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Gallery Image',
                'verbose_name_plural': 'Gallery Images',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='booking',
            name='voucher_code',
            field=models.CharField(blank=True, help_text='Promo code (optional)', max_length=50, verbose_name='Promo Code'),
        ),
    ]
