# Generated by Django 6.0.3 on 2026-04-06 14:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0014_galleryimage_alter_booking_voucher_code'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='galleryimage',
            options={'ordering': ['-created_at'], 'verbose_name': 'Gallery Set', 'verbose_name_plural': 'Gallery Sets'},
        ),
        migrations.RemoveField(
            model_name='galleryimage',
            name='image',
        ),
        migrations.RemoveField(
            model_name='galleryimage',
            name='order',
        ),
        migrations.AlterField(
            model_name='galleryimage',
            name='title',
            field=models.CharField(help_text='Title/description of the gallery set', max_length=100),
        ),
        migrations.CreateModel(
            name='GalleryImageFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Upload gallery image', upload_to='gallery/')),
                ('order', models.IntegerField(default=0, help_text='Display order within the gallery set')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('gallery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='bookings.galleryimage')),
            ],
            options={
                'verbose_name': 'Gallery Image',
                'verbose_name_plural': 'Gallery Images',
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
