# Generated by Django 6.0.3 on 2026-04-06 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0015_alter_galleryimage_options_remove_galleryimage_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='backdrop',
            name='type',
        ),
    ]
