# Generated by Django 6.0.3 on 2026-04-06 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0016_remove_backdrop_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backdrop',
            name='color',
            field=models.CharField(blank=True, editable=False, max_length=20),
        ),
    ]
