# Generated by Django 6.0.3 on 2026-04-07 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0017_alter_backdrop_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='backdrop',
            name='image',
            field=models.ImageField(blank=True, help_text='Upload backdrop image (optional)', null=True, upload_to='backdrops/'),
        ),
    ]
