# Generated by Django 6.0.3 on 2026-04-13 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0018_backdrop_image'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
                DO $$
                BEGIN
                    IF NOT EXISTS (
                        SELECT 1 FROM information_schema.columns
                        WHERE table_name='bookings_booking' AND column_name='payment_method'
                    ) THEN
                        ALTER TABLE bookings_booking
                        ADD COLUMN payment_method VARCHAR(20) DEFAULT 'gcash' NOT NULL;
                    END IF;
                END $$;
            """,
            reverse_sql="""
                ALTER TABLE bookings_booking DROP COLUMN IF EXISTS payment_method;
            """,
            state_operations=[
                migrations.AddField(
                    model_name='booking',
                    name='payment_method',
                    field=models.CharField(choices=[('gcash', 'GCash'), ('cash', 'Cash')], default='gcash', max_length=20),
                ),
            ]
        ),
    ]
