# Generated by Django 6.0.3 on 2026-04-13 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0018_backdrop_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='payment_method',
            field=models.CharField(choices=[('gcash', 'GCash'), ('cash', 'Cash')], default='gcash', max_length=20),
        ),
    ]
