# Generated by Django 6.0.3 on 2026-04-16 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0020_sitesettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galleryimage',
            name='category',
            field=models.CharField(choices=[('solo_snap', 'Solo Snap'), ('twinning_moments', 'Twinning Moments'), ('group_vibes', 'Group Vibes'), ('academic_solo', 'Academic Solo'), ('academic_group', 'Academic Group'), ('super_party', 'Super Party')], default='solo_snap', max_length=50),
        ),
    ]
