# Generated by Django 6.0.3 on 2026-04-16 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0021_update_gallery_category_choices'),
    ]

    operations = [
        migrations.AddField(
            model_name='galleryimage',
            name='quote',
            field=models.CharField(blank=True, help_text='Short quote or caption displayed with this gallery set (optional)', max_length=255),
        ),
    ]
