# Generated by Django 6.0.3 on 2026-04-18 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0023_remove_under_review_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='google_calendar_event_id',
            field=models.CharField(blank=True, editable=False, max_length=100, null=True),
        ),
    ]
