# Generated by Django 6.0.3 on 2026-05-01 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0025_alter_booking_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='package',
            options={'ordering': ['base_price']},
        ),
        migrations.AlterField(
            model_name='booking',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='reference_code',
            field=models.CharField(db_index=True, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('under_review', 'Under Review'), ('paid', 'Paid'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='booking',
            name='time',
            field=models.TimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='package',
            name='base_price',
            field=models.DecimalField(db_index=True, decimal_places=2, max_digits=10),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['date', 'time', 'status'], name='booking_datetime_status_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['status', 'created_at'], name='booking_status_created_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['email'], name='booking_email_idx'),
        ),
        migrations.AddIndex(
            model_name='package',
            index=models.Index(fields=['base_price'], name='package_price_idx'),
        ),
    ]
