# Generated by Django 6.0.3 on 2026-05-09 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0026_add_performance_indexes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galleryimage',
            name='category',
            field=models.CharField(choices=[('solo', 'Solo'), ('couple', 'Couple'), ('group', 'Group'), ('family', 'Family'), ('academic', 'Academic')], default='solo', help_text='Category for filtering in gallery', max_length=50),
        ),
    ]
