# Generated by Django 6.0.3 on 2026-05-14 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0028_add_graduation_prenup_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='booking_advance_days',
            field=models.IntegerField(default=30, help_text='How many days in advance customers can book (e.g., 30 days)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='closing_time',
            field=models.TimeField(default='18:00', help_text='Studio closing time'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='enable_bookings',
            field=models.BooleanField(default=True, help_text='Enable or disable the booking system'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='max_daily_bookings',
            field=models.IntegerField(default=10, help_text='Maximum number of bookings allowed per day (0 = unlimited)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='opening_time',
            field=models.TimeField(default='09:00', help_text='Studio opening time'),
        ),
        migrations.AlterField(
            model_name='galleryimage',
            name='category',
            field=models.CharField(choices=[('solo', 'Solo'), ('couple', 'Twinning'), ('group', 'Group'), ('family', 'Super Party'), ('academic', 'Academic'), ('graduation', 'Graduation'), ('prenup', 'Pre Nup')], default='solo', help_text='Category for filtering in gallery', max_length=50),
        ),
    ]
