# Generated by Django 6.0.3 on 2026-05-14 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0029_sitesettings_booking_advance_days_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='admin_logo',
            field=models.ImageField(blank=True, help_text='Upload admin dashboard logo (recommended: 200×200px, transparent PNG)', null=True, upload_to='admin_logo/'),
        ),
    ]
