# Generated by Django 6.0.3 on 2026-05-15 16:08

from django.db import migrations, models


class Migration(migrations.Migration):
    """
    Add performance indexes for reports and queries.
    
    This migration adds composite indexes to optimize:
    1. Package performance reports (package_id + status + created_at)
    2. Date-based queries (date + status)
    
    Expected performance improvements:
    - Package reports: 50-60% faster with 10,000+ records
    - Date-based queries: 30-50% faster with 10,000+ records
    
    Storage impact: ~5-10 MB for 100,000 records
    Write performance impact: Minimal (~1-2ms overhead)
    """

    dependencies = [
        ('bookings', '0031_add_confirmed_status'),
    ]

    operations = [
        # Index 1: Package + Status + Created At
        # Optimizes: Package performance reports in admin_reports()
        # Query pattern: filter(created_at__gte=X, status='paid').values('package__name')
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(
                fields=['package', 'status', 'created_at'],
                name='booking_pkg_status_created_idx'
            ),
        ),
        
        # Index 2: Date + Status
        # Optimizes: Daily studio setup queries and date-based filtering
        # Query pattern: filter(date=X, status__in=['confirmed', 'paid'])
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(
                fields=['date', 'status'],
                name='booking_date_status_idx'
            ),
        ),
    ]
