# Generated by Django 6.0.4 on 2026-05-19 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0033_remove_pending_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Photo title or description', max_length=200)),
                ('category', models.CharField(choices=[('solo', 'Solo'), ('twinning', 'Twinning'), ('group', 'Group'), ('super-party', 'Super Party'), ('academic', 'Academic')], default='solo', max_length=20)),
                ('image', models.ImageField(help_text='Upload gallery photo', upload_to='gallery/')),
                ('is_active', models.BooleanField(default=True, help_text='Show on website')),
                ('order', models.IntegerField(default=0, help_text='Display order (lower numbers appear first)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Gallery Photo',
                'verbose_name_plural': 'Gallery Photos',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.RemoveField(
            model_name='galleryimagefile',
            name='gallery',
        ),
        migrations.DeleteModel(
            name='GalleryImage',
        ),
        migrations.DeleteModel(
            name='GalleryImageFile',
        ),
    ]
