# Generated by Django 6.0.3 on 2026-05-21 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0034_galleryphoto_remove_galleryimagefile_gallery_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('new_booking', 'New Booking')], default='new_booking', max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('reference_code', models.CharField(blank=True, max_length=20)),
                ('is_read', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
