# Generated by Django 6.0.3 on 2026-05-24 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0035_add_notification_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesettings',
            name='booking_advance_days',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='enable_bookings',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='max_daily_bookings',
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='about_page_image',
            field=models.ImageField(blank=True, help_text='Upload the About page studio image (recommended: 700×450px or similar aspect ratio)', null=True, upload_to='about_page/'),
        ),
    ]
