# Generated by Django 6.0.3 on 2026-06-01 00:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0036_add_about_page_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='creative_package',
        ),
        migrations.DeleteModel(
            name='CreativePackage',
        ),
    ]
