# Generated by Django 6.0.3 on 2026-06-02 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0037_remove_creativepackage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='tier',
        ),
    ]
